name: Python Script2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install polib
      run: pip install polib

    - name: Run Python Script
      run: python tools/po2js.py -../lang/adarkroom.pot
